### ISSUE TITLE
<angular-markdown-editor element not found

### ISSUE THREAD

**Issue by amithashenoyks** [ghiscoding/angular-markdown-editor-demo#1]
core.js:5847 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'angular-markdown-editor'.
1. If 'angular-markdown-editor' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'angular-markdown-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (""markdownText" [(ngModel)]="markdownText"
                                                         [ERROR ->][options]="editorOptions">

**Comment by ghiscoding** [comment]
Sorry but I don't have time to look into this, the library works, we use it in our project with Angular 7. It's just a matter of upgrading this demo to latest Angular and that should work. 

I'd be happy to receive a PR for that

**Comment by jemmali-git** [comment]
@amithashenoyks  may be you have faced this issue   https://github.com/angular/angular-cli/issues/9307#issuecomment-359264655

**Comment by ghiscoding** [comment]
I finally took the time to update it to latest Angular 8

The only problem was to use the correct version of `ngx-markdown`, different Angular version means different `ngx-markdown` compatibility which I have no control over. 

You can reclone the demo and re-run it, it works
